### ISSUE TITLE
Failing to create a bug for expiring variant due to renamed/invalid component name

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1938]
```
2023-03-16 12:20:00,720 - ERROR - Failed to create a bug for the variant `wmf-media-engine`:
{"code":51,"documentation":"https://bmo.readthedocs.io/en/latest/api/","message":"There is no component named 'Audio/Video:Playback' in the 'Core' product.","error":true}
Traceback (most recent call last):
  File "/home/rm_bot/relman-auto-nag/auto_nag/scripts/variant_expiration.py", line 184, in get_bugs
    bug = utils.create_bug(new_bug)
  File "/home/rm_bot/relman-auto-nag/auto_nag/utils.py", line 738, in create_bug
    resp.raise_for_status()
  File "/home/rm_bot/relman-auto-nag/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/bug
```

**Comment by suhaibmujahid** [comment]
This is happening again (see https://bugzilla.mozilla.org/show_bug.cgi?id=1916211#c2). So, we may need the bot to handle that instead of relying on spotting the error in the logs. 

This recently affected the following variants:
- geckoview-no-fission-ship
- geckoview-fission
- geckoview-no-fission
- geckoview-fission-isolate-high-value
