### ISSUE TITLE
[inactive_reviewer] IndexError: list index out of range

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2041]
```
2023-05-04 12:17:11,061 - ERROR - Rule inactive_reviewer
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/inactive_reviewer.py", line 50, in get_bugs
    bugs = super().get_bugs(date, bug_ids, chunk_size)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 455, in get_bugs
    ).get_data().wait()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/bugzilla.py", line 176, in wait
    self.wait_bugs()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/bugzilla.py", line 187, in wait_bugs
    r.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 708, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/bugzilla.py", line 552, in __bugs_cb
    self.bughandler.handle(bug)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/handler.py", line 15, in handle
    self.handler(*args)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 342, in bughandler
    if self.handle_bug(bug, data) is None:
  File "/home/rm_bot/bugbot/bugbot/rules/inactive_reviewer.py", line 245, in handle_bug
    rev_ids = [
  File "/home/rm_bot/bugbot/bugbot/rules/inactive_reviewer.py", line 246, in <listcomp>
    int(PHAB_FILE_NAME_PAT.findall(attachment["file_name"])[0])
IndexError: list index out of range
```

**Comment by suhaibmujahid** [comment]
This happens when the patch is attached manually with a file name that does not match the file name that phab-bot would use:
https://github.com/mozilla/bugbot/blob/2d870ad79f2a6d7af360635f3c7b8e76cd7e925e/bugbot/rules/inactive_reviewer.py#L20 

For example, in https://bugzilla.mozilla.org/show_bug.cgi?id=1825863#c11 a patch was attached manually and the file name that was used is `file_1825863.txt` instead of `phabricator-D177687-url.txt`.
