### ISSUE TITLE
Some rules frequently fail because they cannot get the response from BugBug within the time limit

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2084]
```
2023-05-27 01:43:33,053 - ERROR - Rule regression
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/regression.py", line 63, in get_bugs
    bugs = get_bug_ids_classification("regression", bug_ids)
  File "/home/rm_bot/bugbot/bugbot/bugbug_utils.py", line 58, in get_bug_ids_classification
    raise Exception(msg)
Exception: Couldn't get 83 bug classifications in 147 seconds, aborting
2023-05-27 01:46:26,350 - ERROR - Rule spambug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/spambug.py", line 75, in get_bugs
    bugs = get_bug_ids_classification("spambug", bug_ids)
  File "/home/rm_bot/bugbot/bugbot/bugbug_utils.py", line 58, in get_bug_ids_classification
    raise Exception(msg)
Exception: Couldn't get 11 bug classifications in 147 seconds, aborting
2023-05-27 01:49:16,602 - ERROR - Rule component
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/component.py", line 90, in get_bugs
    bugs = get_bug_ids_classification("component", bug_ids)
  File "/home/rm_bot/bugbot/bugbot/bugbug_utils.py", line 58, in get_bug_ids_classification
    raise Exception(msg)
Exception: Couldn't get 14 bug classifications in 147 seconds, aborting
```

**Comment by marco-c** [comment]
While we figure out if there's something to fix on the bugbug http service side, we could just increase the timeout.

**Comment by suhaibmujahid** [comment]
> While we figure out if there's something to fix on the bugbug http service side, we could just increase the timeout.

The problem is still present after increasing the timeout:
```
2023-06-21 16:51:53,102 - ERROR - Rule component
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 839, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 762, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 680, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/component.py", line 90, in get_bugs
    bugs = get_bug_ids_classification("component", bug_ids)
  File "/home/rm_bot/bugbot/bugbot/bugbug_utils.py", line 72, in get_bug_ids_classification
    raise Exception(msg)
Exception: Couldn't get 5 bug classifications in 210 seconds, aborting
```

Perhaps we should consider increasing it further.
