### ISSUE TITLE
[file_crash_bug] Bad Request for url: https://bugzilla-dev.allizom.org/rest/bug

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2149]
```
2023-07-05 00:42:28,430 - ERROR - Rule file_crash_bug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 844, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 763, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 681, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 192, in get_bugs
    resp.raise_for_status()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla-dev.allizom.org/rest/bug
```

**Comment by suhaibmujahid** [comment]
The following is the error message from Bugzilla:
```
{
    "code": 51,
    "message": "There is no component named 'Audio/Video: Web Codecs' in the 'Core' product.",
    "error": true,
    "documentation": "http://www.bugzilla.org/docs/4.2/en/html/api/"
}
```
This is because the components on bugzilla-dev.allizom.org are not up-to-date with the ones on bugzilla.mozilla.org.

**Comment by suhaibmujahid** [comment]
The `Core::Audio/Video: Web Codecs` component has been added to bugzilla-dev.allizom.org (thanks to @dklawren)
