### ISSUE TITLE
[file_crash_bug] KeyError: 'cf_crash_signature'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2209]
```
2023-08-29 00:42:33,283 - ERROR - Rule file_crash_bug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 844, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 763, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 681, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 88, in get_bugs
    signatures = data_fetcher.analyze()
  File "/home/rm_bot/bugbot/bugbot/crash/analyzer.py", line 909, in analyze
    bugs = self.fetch_bugs()
  File "/home/rm_bot/bugbot/bugbot/crash/analyzer.py", line 883, in fetch_bugs
    ).wait()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/bugzilla.py", line 177, in wait
    super(Bugzilla, self).wait()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/connection.py", line 135, in wait
    r.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/connection.py", line 120, in cb
    query.handler(response, query.handlerdata)
  File "/home/rm_bot/bugbot/bugbot/crash/analyzer.py", line 868, in handler
    for signature in utils.get_signatures(bug["cf_crash_signature"]):
KeyError: 'cf_crash_signature'
```

**Comment by suhaibmujahid** [comment]
This happens because some bugs do not return the `cf_crash_signature` filed. 

### Example: [bug 436817](https://bugzilla.mozilla.org/show_bug.cgi?id=436817)

https://bugzilla.mozilla.org/rest/bug/436817?include_fields=id,cf_crash_signature:
```json
{
  "bugs": [
    {
      "id": 436817
    }
  ],
  "faults": []
}
```

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/2109

**Comment by suhaibmujahid** [comment]
Happening again (see [bug 1854648](https://bugzilla.mozilla.org/show_bug.cgi?id=1854648)): 
```
Product: `Firefox for Metro Graveyard` - Bug 853856 has no cf_crash_signature
Product: `Socorro` - Bug 1852426 has no cf_crash_signature
```

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/2119

**Comment by suhaibmujahid** [comment]
Happening again (see [bug 1868715](https://bugzilla.mozilla.org/show_bug.cgi?id=1868715)):
```
Product: `Infrastructure & Operations Graveyard` - Bug 895845 has no `cf_crash_signature` field
```

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/2144

**Comment by suhaibmujahid** [comment]
Happening again (see [bug 1870988](https://bugzilla.mozilla.org/show_bug.cgi?id=1870988)):
```
Product: `Camino Graveyard` - Bug 707440 has no cf_crash_signature field
```

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/2159

**Comment by suhaibmujahid** [comment]
Happening again (see [bug 1913316](https://bugzilla.mozilla.org/show_bug.cgi?id=1913316)):
```
Product: `Firefox OS Graveyard` - Bug 824777 has no cf_crash_signature
```

**Comment by suhaibmujahid** [comment]
Fixed by https://github.com/mozilla-bteam/bmo/pull/2299
