### ISSUE TITLE
[file_crash_bug] HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://clouseau.moz.tools

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2242]
```
2023-10-13 23:43:16,786 - ERROR - Rule file_crash_bug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 844, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 763, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 681, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 88, in get_bugs
    signatures = data_fetcher.analyze()
  File "/home/rm_bot/bugbot/bugbot/crash/analyzer.py", line 919, in analyze
    clouseau_reports = self.fetch_clouseau_crash_reports()
  File "/home/rm_bot/bugbot/bugbot/crash/analyzer.py", line 765, in fetch_clouseau_crash_reports
    signature_reports = clouseau.Reports.get_by_signatures(
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/clouseau.py", line 65, in get_by_signatures
    ).wait()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/connection.py", line 135, in wait
    r.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/connection.py", line 124, in cb
    res.raise_for_status()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://clouseau.moz.tools/api/reports?signatures=stackoverflow+%7C+RtlpAllocateHeapInternal+%7C+LdrpGetNewTlsVector&signatures=igd10umd64.dll+%7C+RtlpLowFragHeapAllocFromContext&signatures=mozilla%3A%3AThreadBound%3CT%3E%3A%3AAssertIsCorrectThread&signatures=RtlpFreeHeapInternal+%7C+RtlFreeHeap+%7C+free_base+%7C+std%3A%3A_Deallocate%3CT%3E&signatures=%3Cunknown+in+nvwgf2umx.dll%3E+%7C+d3d11.dll+%7C+TargetNtCreateFile64&signatures=libxul.so%400x37cf422+%7C+libxul.so%400x37ce276+%7C+libxul.so%400x37ce100+%7C+libxul.so%400x37cdd0d+%7C+libxul.so%400x3cff820+%7C+libxul.so%400x67ce036+%7C+libxul.so%400x4b3de1d+%7C+libxul.so%400x471720e+%7C+libxul.so%400x3d90c97+%7C+libxul.so%400x3d90966+%7C+libxul.so%400x365b91e+%7C+libxul.so%40...&signatures=gl%3A%3APackParam&signatures=nsPIDOMWindowInner%3A%3AIsCurrentInnerWindow&signatures=libxul.so%400x380cc90+%7C+libxul.so%400x38099e7+%7C+libxul.so%400x3808b86+%7C+libxul.so%400x3808a10+%7C+libxul.so%400x38085bd+%7C+libxul.so%400x3cfba90+%7C+libxul.so%400x67dc176+%7C+libxul.so%400x4b4777d+%7C+libxul.so%400x4564908+%7C+libxul.so%400x3db3a57+%7C+libxul.so%400x3db3726+%7C+libxul.so%40...&signatures=webrender%3A%3Arender_task_graph%3A%3Aimpl%246%3A%3Aindex&signatures=ntdll.dll+%7C+_delayLoadHelper2&signatures=%3Cunknown+in+nvwgf2umx.dll%3E+%7C+CContext%3A%3ATID3D11DeviceContext_SetShader_%3CT%3E&signatures=igd10iumd64.dll+%7C+d3d11.dll+%7C+rx%3A%3ATextureStorage11%3A%3AgetCachedOrCreateSRVForSampler&signatures=____longjmp_chk&signatures=igd10iumd64.dll+%7C+d3d11.dll+%7C+rx%3A%3ABuffer11%3A%3AupdateBufferStorage&signatures=igd10iumd64.dll+%7C+%3Cunknown+in+igd10iumd64.dll%3E+%7C+CContext%3A%3AUMQueryOM_RenderTargets_&signatures=nvwgf2umx.dll+%7C+GlobalMemoryStatusEx&signatures=libxul.so%400x61aa283+%7C+libxul.so%400x6239c90+%7C+libxul.so%400x6238fbf+%7C+libxul.so%400x624f5a2+%7C+libxul.so%400x61e301c+%7C+libxul.so%400x43cbd64+%7C+libxul.so%400x4053bb8+%7C+libxul.so%400x432fd53+%7C+libxul.so%400x35785e7+%7C+libxul.so%400x416af5c+%7C+libxul.so%400x34f300e+%7C+libxul.so%40...&signatures=mozilla%3A%3Alayers%3A%3AShmemTextureData%3A%3ADeallocate&signatures=libxul.so%400x37f37e2+%7C+libxul.so%400x37f2636+%7C+libxul.so%400x37f24c0+%7C+libxul.so%400x37f20cd+%7C+libxul.so%400x3ced440+%7C+libxul.so%400x67cc0f6+%7C+libxul.so%400x4b3ee0d+%7C+libxul.so%400x471725e+%7C+libxul.so%400x3d8d137+%7C+libxul.so%400x3d8ce06+%7C+libxul.so%400x3661ace+%7C+libxul.so%40...&signatures=__GI_memset&signatures=SetEvent+%7C+%3Cunknown+in+igd10iumd64.dll%3E+%7C+CGeometryShader%3A%3ACLS%3A%3AFinalConstruct&signatures=qcdx11arm64xum8180.dll+%7C+d3d11.dll+%7C+dxcore.dll+%7C+ntdll.dll+%7C+kernel32.dll+%7C+mozilla%3A%3Ainterceptor%3A%3AFuncHook%3CT%3E%3A%3Aoperator%28%29&product=Firefox&channel=nightly
```

**Comment by suhaibmujahid** [comment]
It works fine when running it locally.
