### ISSUE TITLE
Failing to crate security crash bugs when having a needinfo on a user outside the `core-security` group

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2261]
```
2023-11-01 12:42:55,958 - ERROR - Failed to create a bug for signature XXXXXXXXXXXXXXXXX: {"documentation":"https://bmo.readthedocs.io/en/latest/api/","message":"You asked Martin Stránský [:stransky] (ni? me) <[xxxxx@xxxx.com](mailto:xxxxx@xxxx.com)> for needinfo on bug 1862416, but that bug has been restricted to users in certain groups, and the user you asked isn't in all the groups to which the bug has been restricted. Please choose someone else to ask, or make the bug accessible to users on its CC: list and add that user to the list.","code":32000,"error":true}
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 212, in get_bugs
    bug = utils.create_bug(bug_data)
  File "/home/rm_bot/bugbot/bugbot/utils.py", line 746, in create_bug
    resp.raise_for_status()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://bugzilla.mozilla.org/rest/bug
```

**Comment by suhaibmujahid** [comment]
@dveditz In such a case, should the bot add the author of the potential regressor to CC or avoid the needinfo altogether?

Note: This will be a fresh bug with no discussions yet (example of a bug filed by the bot: [bug 1862277](https://bugzilla.mozilla.org/show_bug.cgi?id=1862277))
