### ISSUE TITLE
[round_robin_calendar] ValueError: day is out of range for month

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2300]
```
2023-12-14 12:00:52,519 - ERROR - Rule round_robin_fallback
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 649, in parse
    ret = self._build_naive(res, default)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1235, in _build_naive
    naive = default.replace(**repl)
ValueError: day is out of range for month

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/round_robin_fallback.py", line 50, in <module>
    check_people(args.date, dryrun=args.dryrun)
  File "/home/rm_bot/bugbot/bugbot/round_robin_fallback.py", line 25, in check_people
    rr = RoundRobin.get_instance()
  File "/home/rm_bot/bugbot/bugbot/round_robin.py", line 38, in get_instance
    RoundRobin._instances[None] = RoundRobin()
  File "/home/rm_bot/bugbot/bugbot/round_robin.py", line 29, in __init__
    self.feed(None if teams is None else set(teams))
  File "/home/rm_bot/bugbot/bugbot/round_robin.py", line 65, in feed
    calendar = cache[url] = Calendar.get(
  File "/home/rm_bot/bugbot/bugbot/round_robin_calendar.py", line 87, in get
    return JSONCalendar(cal, fallback, team_name, people=people)
  File "/home/rm_bot/bugbot/bugbot/round_robin_calendar.py", line 111, in __init__
    dates = sorted((lmdutils.get_date_ymd(d), d) for d in start_dates.keys())
  File "/home/rm_bot/bugbot/bugbot/round_robin_calendar.py", line 111, in <genexpr>
    dates = sorted((lmdutils.get_date_ymd(d), d) for d in start_dates.keys())
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/libmozdata/utils.py", line 88, in get_date_ymd
    return as_utc(dateutil.parser.parse(dt))
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 651, in parse
    six.raise_from(ParserError(str(e) + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: day is out of range for month: 2023-02-29
```

This issue is impacting the following rules:
- `triage_owner_rotations`
- `workflow/multi_nag`
- `round_robin_fallback`

**Comment by suhaibmujahid** [comment]
I filed a bug to fix the dates in the source: https://bugzilla.mozilla.org/show_bug.cgi?id=1870197

**Comment by gijsk** [comment]
Heh, that's an interesting way to have caught that mistake... if the switchover date hadn't been the 29th we may not have realized...

**Comment by suhaibmujahid** [comment]
> Heh, that's an interesting way to have caught that mistake... if the switchover date hadn't been the 29th we may not have realized...

It would be caught one week before the missed date. Florian would receive an email like the following:
```
Hi there,

The following calendar needs to be updated in order to have a triage owner:

    Performance Engineering: no triage owner for the next week.

Sincerely,
BugBot

See the source / report issues on the [GitHub repo](https://github.com/mozilla/bugbot/)
```
