### ISSUE TITLE
Failing to retrieve the `variants.yml` file

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2390]
```
2024-05-10 12:23:17,782 - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/rm_bot/bugbot/bugbot/rules/variant_expiration.py", line 418, in <module>
    VariantExpiration().run()
  File "/home/rm_bot/bugbot/bugbot/rules/variant_expiration.py", line 98, in __init__
    self.variants = self.get_variants()
  File "/home/rm_bot/bugbot/bugbot/rules/variant_expiration.py", line 137, in get_variants
    resp.raise_for_status()
  File "/home/rm_bot/bugbot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://hg.mozilla.org/mozilla-central/raw-file/tip/taskcluster/ci/test/variants.yml
```

**Comment by suhaibmujahid** [comment]
_From @jmaher on Matrix:_
> @ahal rearranged a bunch of files now it is https://searchfox.org/mozilla-central/source/taskcluster/kinds/test/variants.yml
