### ISSUE TITLE
[file_crash_bug] KeyError: 'cf_status_firefox125'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2396]
```
2024-05-14 00:41:15,729 - ERROR - Rule file_crash_bug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 850, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 766, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 684, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 235, in get_bugs
    updates = bug_analyzer.detect_version_status_updates()
  File "/home/rm_bot/bugbot/bugbot/bug/analyzer.py", line 144, in detect_version_status_updates
    if self._bug[flag] != "---":
KeyError: 'cf_status_firefox125'
```

**Comment by suhaibmujahid** [comment]
Again:

```
2024-07-07 00:40:50,941 - ERROR - Rule file_crash_bug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 856, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 772, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 690, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 235, in get_bugs
    updates = bug_analyzer.detect_version_status_updates()
  File "/home/rm_bot/bugbot/bugbot/bug/analyzer.py", line 144, in detect_version_status_updates
    if self._bug[flag] != "---":
KeyError: 'cf_status_firefox127'
```

Merge day for Firefox 129: July 8, 2024
