### ISSUE TITLE
[regression_set_status_flags] KeyError: 'cf_status_firefox127'

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#2420]
```
2024-06-15 00:43:15,151 - ERROR - Rule regression_set_status_flags
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 850, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 766, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 684, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/regression_set_status_flags.py", line 266, in get_bugs
    bugs = self.get_status_changes(bugs)
  File "/home/rm_bot/bugbot/bugbot/rules/regression_set_status_flags.py", line 162, in get_status_changes
    info[channel] = info[flag]
KeyError: 'cf_status_firefox127'
```

**Comment by suhaibmujahid** [comment]
```
2024-06-11 00:40:57,916 - ERROR - Rule file_crash_bug
Traceback (most recent call last):
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 850, in run
    self.send_email(date=date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 766, in send_email
    data = self.get_email_data(date)
  File "/home/rm_bot/bugbot/bugbot/bzcleaner.py", line 684, in get_email_data
    bugs = self.get_bugs(date=date)
  File "/home/rm_bot/bugbot/bugbot/rules/file_crash_bug.py", line 235, in get_bugs
    updates = bug_analyzer.detect_version_status_updates()
  File "/home/rm_bot/bugbot/bugbot/bug/analyzer.py", line 144, in detect_version_status_updates
    if self._bug[flag] != "---":
KeyError: 'cf_status_firefox126'
```
